routes/web.php
<?php

use App\Http\Controllers\Back\Auth;
use App\Http\Controllers\Front\Captcha;
use App\Http\Controllers\Front\Combo;
use Illuminate\Support\Facades\Route;

//pass admin : 162534
//////*********************************************************FRONT END ROUTES****************************************************** */
//////*************************************************************************************************************************** */

Route::get('/', [\App\Http\Controllers\Front\Home::class, 'index'])->name('index');
Route::get('/konten/{slug}', [\App\Http\Controllers\Front\Konten::class, 'konten'])->name('konten');
Route::get('/profil-pegawai', [\App\Http\Controllers\Front\Profil_pegawai::class, 'profil_pegawai'])->name('profil_pegawai');
Route::get('/hasil-seleksi', [\App\Http\Controllers\Front\Hasil_seleksi::class, 'index'])->name('hasil_seleksi');
Route::get('/hasil-seleksi/{id}', [\App\Http\Controllers\Front\Hasil_seleksi::class, 'detail'])->name('hasil_seleksi_detail');
// Route::get('/profil-pegawai/{slug}', [\App\Http\Controllers\Front\Profil_pegawai::class, 'profil_pegawai'])->name('profil_pegawai');
Route::get('/penempatan', [\App\Http\Controllers\Front\Penempatan::class, 'penempatan'])->name('penempatan');
Route::get('/faq', [\App\Http\Controllers\Front\Faq::class, 'faq'])->name('faq');
Route::get('/pendaftaran', [\App\Http\Controllers\Front\Pendaftaran::class, 'index'])->name('pendaftaran');
Route::post('/pendaftaran', [\App\Http\Controllers\Front\Pendaftaran::class, 'index_post'])->name('pendaftaran_post');
Route::get('/pendaftaran-mtu', [\App\Http\Controllers\Front\Pendaftaran_mtu::class, 'index'])->name('pendaftaran_mtu');
Route::post('/pendaftaran-mtu', [\App\Http\Controllers\Front\Pendaftaran_mtu::class, 'index_post'])->name('pendaftaran_mtu_post');
Route::get('/pendaftaran-pihak-ketiga', [\App\Http\Controllers\Front\Pendaftaran_pihak_ketiga::class, 'index'])->name('pendaftaran_pihak_ketiga');
Route::post('/pendaftaran-pihak-ketiga', [\App\Http\Controllers\Front\Pendaftaran_pihak_ketiga::class, 'index_post'])->name('pendaftaran_pihak_ketiga_post');
Route::get('/katalog-alumni', [\App\Http\Controllers\Front\Katalog::class, 'index'])->name('katalog_alumni');
Route::post('/api/login_as_alumni', [\App\Http\Controllers\Front\Api::class, 'login_as_alumni'])->name('login_as_alumni');
// Route::get('/katalog-alumni/produk', [\App\Http\Controllers\Front\Katalog::class, 'katalog_produk'])->name('katalog_produk');
// Route::get('/katalog-alumni/produk/{slug}', [\App\Http\Controllers\Front\Katalog::class, 'katalog_produk_detail'])->name('katalog_produk_detail');
// Route::get('/katalog-alumni/jasa', [\App\Http\Controllers\Front\Katalog::class, 'katalog_jasa'])->name('katalog_jasa');
// Route::get('/katalog-alumni/jasa/{slug}', [\App\Http\Controllers\Front\Katalog::class, 'katalog_jasa_detail'])->name('katalog_jasa_detail');

Route::get('/publikasi/pengumuman', [\App\Http\Controllers\Front\Pengumuman::class, 'index'])->name('pengumuman_index');
Route::get('/publikasi/pengumuman/{id}', [\App\Http\Controllers\Front\Pengumuman::class, 'pengumuman_detail'])->name('pengumuman_detail');
// Route::get('/publikasi/pengumuman/{slug}', [\App\Http\Controllers\Front\Publikasi::class, 'pengumuman_detail'])->name('pengumuman_detail');
Route::get('/program-kegiatan', [\App\Http\Controllers\Front\Program_kegiatan::class, 'program_kegiatan'])->name('program_kegiatan');
Route::get('/program-kegiatan/{slug}', [\App\Http\Controllers\Front\Program_kegiatan::class, 'program_kegiatan_detail'])->name('program_kegiatan_detail');
Route::get('/info-lowongan', [\App\Http\Controllers\Front\Info_lowongan::class, 'info_lowongan'])->name('info_lowongan');
Route::get('/info-lowongan/detail/{id}', [\App\Http\Controllers\Front\Info_lowongan::class, 'detail'])->name('info_lowongan_detail');
Route::get('/galeri', [\App\Http\Controllers\Front\Galeri::class, 'index'])->name('galeri');
Route::get('/galeri/detail/{id}', [\App\Http\Controllers\Front\Galeri::class, 'detail'])->name('galeri_detail');
Route::get('/agenda', [\App\Http\Controllers\Front\Agenda::class, 'index'])->name('agenda');
Route::get('/agenda/{slug}', [\App\Http\Controllers\Front\Agenda::class, 'detail'])->name('agenda_detail');
// Route::get('/agenda/{id}', [\App\Http\Controllers\Front\Publikasi::class, 'agenda_detail'])->name('agenda_detail');
Route::get('/pengaduan', [\App\Http\Controllers\Front\Pengaduan::class, 'pengaduan'])->name('pengaduan');
Route::post('/pengaduan_post', [\App\Http\Controllers\Front\Pengaduan::class, 'pengaduan_post'])->name('pengaduan_post');
Route::get('/reload-captcha', [Captcha::class, 'reloadCaptcha'])->name('reload_captcha');
Route::post('/get_combo_kota', [Combo::class, 'get_combo_kota'])->name('get_combo_kota');
Route::post('/get_combo_kecamatan', [Combo::class, 'get_combo_kecamatan'])->name('get_combo_kecamatan');
Route::post('/get_combo_kelurahan', [Combo::class, 'get_combo_kelurahan'])->name('get_combo_kelurahan');
Route::post('/get_combo_kejuruan', [Combo::class, 'get_combo_kejuruan'])->name('get_combo_kejuruan');
Route::post('/get_jenis_disabilitas', [Combo::class, 'get_jenis_disabilitas'])->name('get_jenis_disabilitas');
Route::post('/get_pelatihan_dibuka', [Combo::class, 'get_pelatihan_dibuka'])->name('get_pelatihan_dibuka');
Route::post('/get_gelombang_dibuka', [Combo::class, 'get_gelombang_dibuka'])->name('get_gelombang_dibuka');
Route::post('/get_cbt_grup_id', [Combo::class, 'get_cbt_grup_id'])->name('get_cbt_grup_id');

Route::get('/kejuruan', [\App\Http\Controllers\Front\Kejuruan::class, 'index'])->name('kejuruan');
Route::get('/tipe-pelatihan', [\App\Http\Controllers\Front\Tipe_pelatihan::class, 'index'])->name('tipe_pelatihan');
Route::get('/program-pelatihan', [\App\Http\Controllers\Front\Program_pelatihan::class, 'home'])->name('program_pelatihan_home');
Route::get('/program-pelatihan/{id}', [\App\Http\Controllers\Front\Program_pelatihan::class, 'index'])->name('program_pelatihan');
Route::get('/program-pelatihan-detil/{id}', [\App\Http\Controllers\Front\Program_pelatihan::class, 'detail'])->name('program_pelatihan_detil');
Route::get('/jadwal', [\App\Http\Controllers\Front\Jadwal::class, 'index'])->name('jadwal');
Route::get('/send_email_pendaftaran', [\App\Http\Controllers\Front\Email::class, 'send_email_pendaftaran'])->name('send_email_pendaftaran');

Route::get('/alumni/login', [\App\Http\Controllers\Front\Alumni::class, 'alumni_login'])->name('alumni_login');
Route::post('/alumni/login', [\App\Http\Controllers\Front\Alumni::class, 'alumni_login_post'])->name('alumni_login_post');
Route::get('/alumni/daftar', [\App\Http\Controllers\Front\Alumni::class, 'alumni_daftar'])->name('alumni_daftar');
Route::post('/alumni/daftar', [\App\Http\Controllers\Front\Alumni::class, 'alumni_daftar_post'])->name('alumni_daftar_post');
Route::post('/alumni/get_nik', [\App\Http\Controllers\Front\Alumni::class, 'alumni_get_nik'])->name('alumni_get_nik');
Route::get('/aktivasi_alumni', [\App\Http\Controllers\Front\Alumni::class, 'aktivasi_alumni'])->name('aktivasi_alumni');
Route::post('/load_jadwal_available', [\App\Http\Controllers\Back\Transaksi_wawancara::class, 'load_jadwal_available'])->name('load_jadwal_available');



Route::group([
    'prefix' => 'alumni_page',
    'as' => 'alumni_page.',
    'middleware' => ['ceklogin_alumni'],
], function (){
    
    Route::get('/', [\App\Http\Controllers\Front\Alumni::class, 'alumni_dashboard'])->name('dashboard');
    Route::get('/edit-profil', [\App\Http\Controllers\Front\Alumni::class, 'edit_profil'])->name('edit_profil');
    Route::post('/edit-profil', [\App\Http\Controllers\Front\Alumni::class, 'edit_profil_post'])->name('edit_profil_post');
    Route::get('/dashboard', [\App\Http\Controllers\Front\Alumni::class, 'alumni_dashboard'])->name('dashboard');
    Route::get('/logout', [\App\Http\Controllers\Front\Alumni::class, 'logout'])->name('logout');
    Route::get('/reset_password', [\App\Http\Controllers\Front\Alumni::class, 'edit_profil'])->name('edit_profil');
    Route::post('/reset_password', [\App\Http\Controllers\Front\Alumni::class, 'edit_profil_post'])->name('edit_profil_post');
    
    Route::group([
        'prefix' => 'pekerjaan',
        'as' => 'pekerjaan.',
    ], function (){
        Route::get('/', [\App\Http\Controllers\Front\Alumni_pekerjaan::class, 'index'])->name('index');
        Route::post('/datatable', [\App\Http\Controllers\Front\Alumni_pekerjaan::class, 'datatable'])->name('datatable');
        Route::post('/add', [\App\Http\Controllers\Front\Alumni_pekerjaan::class, 'add'])->name('add');
        Route::post('/save', [\App\Http\Controllers\Front\Alumni_pekerjaan::class, 'save'])->name('save');
        Route::post('/delete', [\App\Http\Controllers\Front\Alumni_pekerjaan::class, 'delete'])->name('delete');
    });
    
    Route::group([
        'prefix' => 'usaha',
        'as' => 'usaha.',
    ], function (){
        Route::get('/', [\App\Http\Controllers\Front\Alumni_usaha::class, 'index'])->name('index');
        Route::post('/datatable', [\App\Http\Controllers\Front\Alumni_usaha::class, 'datatable'])->name('datatable');
        Route::post('/add', [\App\Http\Controllers\Front\Alumni_usaha::class, 'add'])->name('add');
        Route::post('/save', [\App\Http\Controllers\Front\Alumni_usaha::class, 'save'])->name('save');
        Route::post('/delete', [\App\Http\Controllers\Front\Alumni_usaha::class, 'delete'])->name('delete');
    });

});


//////*********************************************************BACK END ROUTES****************************************************** */
//////*************************************************************************************************************************** */




// Route::get('/daftar', [\App\Http\Controllers\Front\Home::class, 'daftar'])->name('daftar');
// Route::post('/daftar_post', [\App\Http\Controllers\Front\Home::class, 'daftar_post'])->name('daftar_post');

app/Http/Controllers/Front/Agenda.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\M_agenda;
use Illuminate\Http\Request;

class Agenda extends Controller
{
    public function index()
    {
        $data = [
            'agenda' => M_agenda::orderByDesc('id_m_agenda')->where('aktif_m_agenda', '1')->paginate(9),
        ];

        return view('front.agenda.index')->with($data);
    }
    
    
    public function detail($slug)
    {
        abort_if($slug == null, 404);
        $data = [
            'agenda' => M_agenda::where('slug_m_agenda', $slug)->where('aktif_m_agenda', '1')->firstOrFail(),
        ];

        return view('front.agenda.detail')->with($data);
    }
}

app/Http/Controllers/Front/Alumni_pekerjaan.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Carbon\Carbon;
use App\Http\Controllers\Controller;
use App\Models\M_bidang_usaha;
use App\Models\M_link_cepat;
use App\Models\M_provinsi;
use App\Models\T_pekerjaan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Alumni_pekerjaan extends Controller
{
    public function index()
    {
        $data = [
            'head_title' => 'Data Pekerjaan Alumni',
            'page_title' => 'Data Pekerjaan Alumni',
            'parent_menu_active' => 'Alumni',
            'child_menu_active'   => 'Data Pekerjaan Alumni',
        ];

        return view('front.alumni.pekerjaan.index')->with($data);
    }

    public function add()
    {
        $provinsi = M_provinsi::select('id_m_provinsi','nm_m_provinsi')->orderBy('nm_m_provinsi')->get();
        $data = [
            'head_title' => 'Data Pekerjaan Alumni',
            'page_title' => 'Data Pekerjaan Alumni',
            'parent_menu_active' => 'Alumni',
            'child_menu_active'   => 'Data Pekerjaan Alumni',
            'bidang_usaha' => M_bidang_usaha::where('aktif', '1')->get(),
            'id_m_provinsi' => $provinsi,
        ];

    	return view('front.alumni.pekerjaan.add')->with($data);
    }

    public function save(Request $request)
    {
        $messages = [
            'nm_t_pekerjaan.required' => 'harap diisi',
            'id_m_bidang_usaha.required' => 'harap diisi',
            'jabatan_t_pekerjaan.required' => 'harap diisi',
            'id_m_provinsi.required' => 'harap diisi',
            'id_m_kota.required' => 'harap diisi',
            'id_m_kecamatan.required' => 'harap diisi',
            // 'captcha.captcha' => 'kode salah',
            // 'captcha.required' => 'harap diisi',
        ];

        $validator = Validator::make($request->all(), [
            'nm_t_pekerjaan' => ['required'],
            'id_m_bidang_usaha' => ['required'],
            'jabatan_t_pekerjaan' => ['required'],
            'id_m_provinsi' => ['required'],
            'id_m_kota' => ['required'],
            'id_m_kecamatan' => ['required'],
            // 'captcha' => 'required|captcha',
        ], $messages);

        if ($validator->fails()) {
            $errors = $validator->errors();
            return response()->json([
                'error' => [
                    'nm_t_pekerjaan' => $errors->first('nm_t_pekerjaan'),
                    'id_m_bidang_usaha' => $errors->first('id_m_bidang_usaha'),
                    'jabatan_t_pekerjaan' => $errors->first('jabatan_t_pekerjaan'),
                    'id_m_provinsi' => $errors->first('id_m_provinsi'),
                    'id_m_kota' => $errors->first('id_m_kota'),
                    'id_m_kecamatan' => $errors->first('id_m_kecamatan'),
                    // 'captcha' => $errors->first('captcha'),
                ]
            ]);
        }


        DB::beginTransaction();
        $object = new T_pekerjaan;
        $object->id_t_pekerjaan = T_pekerjaan::MaxId();
        $object->nm_t_pekerjaan = $request->nm_t_pekerjaan;
        $object->jabatan_t_pekerjaan = $request->jabatan_t_pekerjaan;
        $object->telp_t_pekerjaan = $request->telp_t_pekerjaan;
        $object->tgl_mulai_bekerja = ($request->tgl_mulai_bekerja) ? Carbon::parse($request->tgl_mulai_bekerja)->format('Y-m-d') : null;
        $object->alamat_t_pekerjaan = $request->alamat_t_pekerjaan;
        $object->id_m_kecamatan = $request->id_m_kecamatan;
        $object->id_m_alumni = $request->id_m_alumni;
        $object->id_m_bidang_usaha = $request->id_m_bidang_usaha;

        try{
       
            $object->save();
            DB::commit();
            return response()->json([
                'status' => true,
                'message' => 'Data pekerjaan berhasil disimpan',
                'redirect' => route('alumni_page.pekerjaan.index'),
            ]);
        }catch(\Exception $e){
            DB::rollback();
            return response()->json([
                'message' => $e->getMessage(),
                'status'  => false,
            ]);
        }

    }



    public function delete(Request $request)
    {
        if(!$request->filled('id_t_pekerjaan')){
            return response()->json([
                'message' => 'parameter invalid !',
                'status'  => false,
            ]);
        }

        $find = T_pekerjaan::where([
            'id_t_pekerjaan' => $request->id_t_pekerjaan
        ])->first();

        if($find==null){
            return response()->json([
                'message' => 'parameter invalid !',
                'status'  => false,
            ]);
        }

        DB::beginTransaction();

        try{
            $find->delete();
            DB::commit();
            return response()->json([
                'status' => true,
                'redirect' => route('alumni_page.pekerjaan.index'),
            ]);
        }catch(\Exception $e){
            DB::rollback();
            return response()->json([
                'message' => $e->getMessage(),
                'status'  => false,
            ]);
        }

        return response()->json([
            'message' => 'Server error',
            'status'  => false,
        ]);
    }



    public function datatable(Request $request)
    {
        $table = T_pekerjaan::where('id_m_alumni', session()->get('alumni_logged_in.id_m_alumni'))
                ->with('bidang')
                ->orderByDesc('id_t_pekerjaan')->get();
    	$datas = [];
    	$i = 1;
    	foreach ($table as $key => $value) {

    		$datas[$key][] = $i++;
            $datas[$key][] = $value->nm_t_pekerjaan;
            $datas[$key][] = $value->bidang->nm_m_bidang_usaha;
            $datas[$key][] = $value->tgl_mulai_bekerja;
            $datas[$key][] = $value->jabatan_t_pekerjaan;
            $datas[$key][] = $value->telp_t_pekerjaan;
            $datas[$key][] = '<a class="btn-sm btn-danger delete" data-id_t_pekerjaan="'.$value->id_t_pekerjaan.'" href="#">hapus</a>';
    	}
        // die();

    	$data = [
    		'data' => $datas
    	];

    	return response()->json($data);
    }
}

app/Http/Controllers/Front/Api.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\M_alumni;
use Carbon\Carbon;
use Illuminate\Http\Request;

class Api extends Controller
{
    public function login_as_alumni(Request $request)
    {
        $get = M_alumni::where('nik_m_alumni', $request->username)->first();
        if($get){
            $success = TRUE;
        }else{
            $success = FALSE;
        }
        return response()->json([
            'success' => $success,
            'data' => $get
        ]);
    }
}

app/Http/Controllers/Front/Captcha.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Captcha extends Controller
{
    public function reloadCaptcha()
    {
        return response()->json(['captcha'=> captcha_img()]);
    }
}

resources/views/front/alumni/alumni_dashboard.blade.php
@extends('front.template.index_detail')

@section('content')

<style>
    .swal2-popup {
      font-size: 1.4rem!important;
    }
    .box_red{
        background-color: #F9F7F7!important;
        padding: 15px;margin: 10px 1px; 
        border-radius: 5px;
        border:1px solid #F4F0F0;
        box-shadow: 0px 2px 5px 0px rgb(0 0 0 / 10%);
        margin-bottom: 15px!important;
        cursor: pointer;
        transition: all .3s ease;
    }
    .box_red:hover{
        background: #ffffff!important;
    }
    .box_red a{
        color: black;
        font-size: 16px;
    }
  </style>
@php
    $bg = \App\Models\M_bg::where('slug_m_bg', 'faq')->first();
@endphp
<section class="page-title text-center" 
@if(isset($bg->photo) and $bg->aktif_m_bg == '1') style="background-image: url({{asset('storage'.'/'.$bg->photo)}});" 
@else style="background-image: url({{asset('assets/front/images/1647919128_bg-blk.jpg')}});"
@endif
role="banner">
<div class="title-overlay-color"></div>
    <div class="container">
        <h1 style="">Halaman Utama - Alumni</h1>
        <div class="tt-breadcrumb" style="">
            <ul class="breadcrumb">
                <li><a href="{{url('/')}}">Home</a></li>
                <li class="active">Halaman Utama - Alumni</li>
            </ul>
        </div>
    </div>
</section>


<section class="vc_row section-wrapper" style="margin-bottom: 30px;">
    <div class="container">
        <div class="row">
            <div class="wpb_column vc_column_container vc_col-sm-12">
                <div class="vc_column-inner">
                    <div class="wpb_wrapper">
                        
                        <div class="wpb_text_column wpb_content_element vc_custom_1459914002700">
                            <div class="wpb_wrapper">
                                    


                                <div class="panel-group" id="accordionGroupOpen" role="tablist" aria-multiselectable="true">
                                    <div class="row">
                                        <div class="col-md-3" 
                                            style="margin: 0 auto;">
                                            <div class="box_red" onclick="location.href='{{route('alumni_page.edit_profil')}}'">
                                                <a href="javascript:void(0)"><img src="{{asset('assets/front/images/resume.png')}}" height="40" />&nbsp;&nbsp; Ubah Profil Alumni</a>
                                            </div>
                                        </div>
                                        {{--<div class="col-md-3" 
                                            style="margin: 0 auto;">
                                            <div class="box_red" onclick="location.href='{{route('alumni_page.edit_profil')}}'">
                                                <a href="#"><img src="{{asset('assets/front/images/loading.png')}}" height="40" />&nbsp;&nbsp; Reset Password</a>
                                            </div>
                                        </div>--}}
                                        {{-- <div class="col-md-3" 
                                            style="margin: 0 auto;">
                                            <div class="box_red" onclick="location.href='{{route('alumni_page.edit_profil')}}'">
                                                <a href="#"><img src="{{asset('assets/front/images/certificate.png')}}" height="40" />&nbsp;&nbsp; Download Sertifikat</a>
                                            </div>
                                        </div> --}}
                                        <div class="col-md-3" 
                                            style="margin: 0 auto;">
                                            <div class="box_red" onclick="location.href='{{route('alumni_page.pekerjaan.index')}}'">
                                                <a href="{{route('alumni_page.pekerjaan.index')}}"><img src="{{asset('assets/front/images/job-loss.png')}}" height="40" />&nbsp;&nbsp; Data Pekerjaan</a>
                                            </div>
                                        </div>
                                        <div class="col-md-3" 
                                            style="margin: 0 auto;">
                                            <div class="box_red" onclick="location.href='{{route('alumni_page.usaha.index')}}'">
                                                <a href="{{route('alumni_page.usaha.index')}}"><img src="{{asset('assets/front/images/my-business.png')}}" height="40" />&nbsp;&nbsp; Data Usaha</a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>


                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

@endsection

@section('js')
<script>
$("#form").submit(function(){
    $(".text-danger").remove();
    event.preventDefault();
    var data = new FormData($('#form')[0]);
    var catValue = '{{request()->get('cat')}}';
    data.append('cat', catValue);
    $("#submitform").attr('disabled', true);
    $("#submitform span").text(loading_text);

    $.ajax({
        url:"{{ route("alumni_daftar_post") }}",
        method:"post",
        headers: { "X-CSRF-TOKEN": $("meta[name=csrf-token]").attr("content") },
        data: data,
        processData: false,
        contentType: false,
        success:function(data)
        {
            if($.isEmptyObject(data.error)){
                if(data.status == true){
                    $("#submitform").removeAttr('disabled');
                    $("#submitform span").text('Daftar Sekarang');
                    $("form").each(function() { this.reset() });
                    swal.fire({
                        title: "Success",
                        text: data.message,
                        icon: "success"
                    }).then(function() {
                        location.href = data.redirect;
                    });
                }else{
                    displayWarningSwal(data.message);
                    reload_captcha();
                    $("#submitform").removeAttr('disabled');
                    $("#submitform span").text('Daftar Sekarang');
                }

            }else{
                displayWarningSwal();
                reload_captcha();
                $("#submitform").removeAttr('disabled');
                $("#submitform span").text('Daftar Sekarang');
                $.each(data.error, function(key, value) {
                    var element = $("#" + key);
                    element.closest("div.form-control")
                    .removeClass("text-danger")
                    .addClass(value.length > 0 ? "text-danger" : "")
                    .find("#error_" + key).remove();
                    element.after("<div id=error_"+ key + " class=text-danger>" + value + "</div>");
                });
            }
        },
        error: function(data){
            displayErrorSwal(data.message);
        }
    });
});


$('#ceknik').click(function(){
    var nik_m_alumni = $('#nik_m_alumni').val();
    $("#ceknik").attr('disabled', true);
    $("#ceknik span").text(loading_text);
    $.ajax({
        url:"{{ route("alumni_get_nik") }}",
        method:"post",
        datatype: 'json',
        headers: { "X-CSRF-TOKEN": $("meta[name=csrf-token]").attr("content") },
        data: {
            nik_m_alumni: nik_m_alumni
        },
        success:function(data)
        {
            if(data.status == true){
                $("#ceknik").removeAttr('disabled');
                $("#ceknik span").text('Cek NIK');
                $("#nm_m_alumni").val(data.text);
            }else{
                displayWarningSwal(data.message);
                $("#nm_m_alumni").val('');
                $("#ceknik").removeAttr('disabled');
                $("#ceknik span").text('Cek NIK');
            }

        },
        error: function(data){
            displayErrorSwal(data.message);
        }
    });
})
</script>
@endsection